---
- name: Create geoprocessing directory
  file: path="{{ geop_home }}"
        state=directory

- name: Download mmw-geoprocessing JAR
  get_url: url="{{ geop_jar_url }}"
           dest="{{ geop_home }}/mmw-geoprocessing-{{ geop_version }}.jar"

- name: Configure Nginx site
  template: src=nginx-geoprocessing.conf.j2
            dest=/etc/nginx/sites-available/geoprocessing.conf
  notify:
    - Restart Nginx

- name: Enable Nginx site
  file: src=/etc/nginx/sites-available/geoprocessing.conf
        dest=/etc/nginx/sites-enabled/geoprocessing
        state=link
  notify:
    - Restart Nginx

- name: Enable Nginx service
  service: name=nginx.service enabled=yes

- name: Configure geoprocessing service definition
  template: src=systemd-geoprocessing.service.j2
            dest=/etc/systemd/system/mmw-geoprocessing.service
  notify:
    - Restart geoprocessing service

- name: Enable geoprocessing service
  systemd: name=mmw-geoprocessing.service enabled=yes state=started daemon_reload=yes
