---
- name: Configure application
  copy: content="{{ item.value }}"
        dest="{{ envdir_home }}/{{ item.key }}"
        owner=root
        group=mmw
        mode=0440
  with_dict: "{{ app_config }}"
  notify:
    - Restart mmw-app

- name: Configure Gunicorn settings
  template: src=gunicorn.py.j2 dest=/etc/mmw.d/gunicorn.py
  notify:
    - Restart mmw-app

- name: Configure Gunicorn service definition
  template: src=systemd-app.service.j2
            dest=/etc/systemd/system/mmw-app.service
  notify:
    - Restart mmw-app

- name: Enable Gunicorn service
  systemd: name=mmw-app.service enabled=yes state=started daemon_reload=yes
