---
- name: Install numba
  pip: name="{{ item.name }}" version={{ item.version }} state=present executable=pip
  with_items:
    - { name: "llvmlite", version: "{{ llvmlite_version }}" }
    - { name: "numba", version: "{{ numba_version }}" }

- name: Install application Python dependencies for development and test
  pip: requirements="{{ app_home }}/requirements/{{ item }}.txt" executable=pip
  with_items:
    - development
    - test
  when: "['development', 'test'] | some_are_in(group_names)"
  notify:
    - Restart mmw-app

- name: Install application Python dependencies for production
  pip: requirements="{{ app_home }}/requirements/production.txt" executable=pip
  when: "['packer'] | is_in(group_names)"
  notify:
    - Restart mmw-app

- name: Hack Python 2.7 to work with Ubuntu Focal
  replace:
    path: /usr/local/lib/python2.7/dist-packages/django/contrib/gis/geos/libgeos.py
    regexp: geos_version\(\)\.decode\(\)
    replace: geos_version().strip().decode()
