---
- name: Install Geospatial libraries
  apt:
    pkg: ["binutils=2.38*",
          "libproj-dev=8.2.*",
          "gdal-bin=3.4.*",
          "libgdal-dev=3.4.*"]
    state: present
  when: "['tile-servers'] | is_not_in(group_names)"

- name: Configure the main PostgreSQL APT repository
  apt_repository: repo="deb [arch=amd64] https://apt-archive.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg-archive {{ postgresql_support_repository_channel }}"
                  state=present

- name: Install PostgreSQL client
  apt: pkg=postgresql-client-{{ postgresql_version }}={{ postgresql_package_version }}
