- name: Download Papertrail root certificate
  get_url:
    url: https://papertrailapp.com/tools/papertrail-bundle.pem
    dest: /etc/papertrail-bundle.pem
    checksum: sha256:ae31ecb3c6e9ff3154cb7a55f017090448f88482f0e94ac927c0c67a1f33b9cf

- name: Install rsyslog TLS utils
  apt: name=rsyslog-gnutls
