---
- name: Configure remote_syslog
  template: src="log_files.yml.j2"
            dest="{{ papertrail_conf }}"
  notify:
    - Restart remote_syslog

- name: Add Papertrail user to service group
  user: name=papertrail
        append=yes
        groups=adm
        state=present
