- name: Add Python3 dependencies
  apt:
    pkg: software-properties-common
    state: present

- name: Add Deadsnakes PPA
  apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Install Python{{ python_version }}
  apt:
    pkg: ["python{{ python_version }}",
          "python{{ python_version }}-dev",
          "python{{ python_version }}-distutils"]
    state: present

- name: Replace default Python3
  alternatives:
    name: python
    link: /usr/bin/python3
    path: /usr/bin/python{{ python_version }}

- name: Download get-pip.py
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py

- name: Install pip
  command: "python{{ python_version }} /tmp/get-pip.py"
  become: yes

- name: Install old setuptools with use_2to3 support
  pip: name=setuptools
       version=<58
       state=present
