- name: Install Python 2.7
  apt:
    pkg: ["python2={{ python_version }}",
          "python2-dev={{ python_version }}"]
    state: present

- name: Install pip
  shell: curl -sL https://bootstrap.pypa.io/pip/2.7/get-pip.py | sudo python
  args:
    warn: no
