# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('user', '0007_userprofile_unit_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcordUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('concord_id', models.IntegerField()),
            ],
        ),
    ]
