# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-21 02:19
import apps.modeling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0030_custom_weather_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='weather_type',
            field=models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('SIMULATION', 'SIMULATION'), ('CUSTOM', 'CUSTOM')], default='DEFAULT', help_text='The source of weather data for this scenario. Only applies to GWLF-E scenarios.', max_length=255),
        ),
        migrations.AddField(
            model_name='scenario',
            name='weather_simulation',
            field=models.CharField(help_text='Identifier of the weather simulation to use.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='weather_custom',
            field=models.FileField(help_text='Reference path of the custom weather file.', null=True, upload_to=apps.modeling.models.scenario_filename),
        ),
    ]
