# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-06 20:55
from __future__ import unicode_literals

from django.db import migrations


def delete_empty_aoi_projects(apps, schema_editor):
    """Deletes non-activity projects with NULL Areas of Interest"""

    db_alias = schema_editor.connection.alias
    Project = apps.get_model('modeling', 'Project')

    Project.objects.using(db_alias)\
        .filter(area_of_interest=None,
                is_activity=False)\
        .delete()


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0032_project_remove_weather_fields'),
    ]

    operations = [
        migrations.RunPython(delete_empty_aoi_projects),
    ]
