# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-06 21:03
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0033_delete_empty_aoi_projects'),
    ]

    operations = [
        migrations.RunSQL('''
            ALTER TABLE modeling_project
            ADD CONSTRAINT if_not_activity_then_aoi_not_null
            CHECK ( is_activity OR ( area_of_interest IS NOT NULL ) );
        ''')
    ]
