# Generated by Django 3.2.10 on 2021-12-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0037_layer_overrides_streams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='layer_overrides',
            field=models.JSONField(default=dict, help_text='JSON object of layers to override defaults with'),
        ),
    ]
