# Generated by Django 3.2.25 on 2025-05-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0041_clear_nlcd2019_gwlfe_results'),
    ]

    operations = [
        migrations.RunSQL('''
            INSERT INTO spatial_ref_sys (srid, auth_name, auth_srid, proj4text, srtext)
            SELECT
                54017,
                'ESRI',
                54017,
                '+proj=cea +lat_ts=30 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +type=crs',
                'PROJCS["World_Behrmann",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["standard_parallel_1",30],PARAMETER["central_meridian",0],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["ESRI","54017"]]'
            WHERE NOT EXISTS (
                SELECT *
                FROM spatial_ref_sys
                WHERE srid = 54017
            )
        ''')
    ]
