# Generated by Django 3.2.25 on 2025-06-05 20:09
import json
from django.db import migrations


def remove_sedaadjust_from_tr55_scenarios(apps, schema_editor):
    """
    Remove mistakenly added 'SedAAdjust' entry from TR-55 modifications, marked
    by 'entry_other'. This was added in 0039_override_sedaadjust_for_old_scenarios.py
    """
    Scenario = apps.get_model('modeling', 'Scenario')

    filtered_scenarios = Scenario.objects.filter(
        project__model_package='tr-55',
        modifications__contains='SedAAdjust')

    for s in filtered_scenarios:
        mods = json.loads(s.modifications)
        cleaned_mods = [m for m in mods if m.get('modKey') != 'entry_other']
        s.modifications = json.dumps(cleaned_mods)
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0042_postgis_add_ESRI54017'),
    ]

    operations = [
        migrations.RunPython(remove_sedaadjust_from_tr55_scenarios),
    ]
