# Generated by Django 3.2.25 on 2025-09-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0043_remove_sedaadjust_from_tr55_scenarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='pointsource_type',
            field=models.CharField(choices=[('conus', 'Continental US Point Source Data (NPDES)'), ('drb', 'Delaware River Basin Point Source Data (NPDES)'), ('pa', 'Pennsylvania Point Source Data (NPDES)')], default=None, help_text='The source of point source data for this scenario. Only applies to GWLF-E scenarios.', max_length=255, null=True),
        ),
    ]
