# Generated by Django 3.2.25 on 2025-09-15 19:30

from django.db import migrations
from django.db.models import Case, When, F
from django.conf import settings

def initialize_pointsource_types(apps, schema_editor):
    """
    Populate initial pointsource_type values to existing Scenario instances
    based on the below conditions:
    DRB
     - Scenario project's model_package is gwlfe
     - Scenario project's area_of_interest is within DRB
    CONUS
     - Scenario project's model_package is gwlfe
     - Scenario project's area_of_interest is within CONUS
    NULL
     - Default
    
    Note that at this time there are no rows that meet the conditions of PA
    as this migration is part of the work to support PA point source data.
    """
    Scenario = apps.get_model('modeling', 'Scenario')

    Scenario.objects.filter(
        project__model_package='gwlfe',
        project__area_of_interest__within=settings.PERIMETERS['CONUS']['geom']
    ).update(pointsource_type='conus')

    Scenario.objects.filter(
        project__model_package='gwlfe',
        project__area_of_interest__within=settings.PERIMETERS['DRB_SIMPLE']['geom']
    ).update(pointsource_type='drb')

def reset_pointsource_types(apps, schema_editor):
    Scenario = apps.get_model('modeling', 'Scenario')
    Scenario.objects.all().update(pointsource_type=None)

class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0044_add_pointsource_type'),
    ]

    operations = [
        migrations.RunPython(initialize_pointsource_types, reset_pointsource_types),
    ]
