# Generated by Django 3.2.25 on 2025-09-16 18:54

import json
from django.db import migrations, models


BASE_SIMULATIONS = [
    {
        'group': 'Recent Weather',
        'items': [
            {'name': 'NASA_NLDAS_2000_2019', 'label': 'NASA NLDAS 2000-2019'}
        ],
        'eligible_area': 'DRWI or PA',
        'disabled': True,
    },
    {
        'group': 'Future Weather Simulations',
        'items': [
            {'name': 'RCP45_2080_2099', 'label': 'RCP 4.5 2080-2099'},
            {'name': 'RCP85_2080_2099', 'label': 'RCP 8.5 2080-2099'},
        ],
        'eligible_area': 'DRB',
        'disabled': True,
    },
]

WEATHER_SIMULATIONS = {
    'neither': [
        {**sim, 'disabled': True} for sim in BASE_SIMULATIONS
    ],
    'recent': [
        {**BASE_SIMULATIONS[0], 'disabled': False},
        {**BASE_SIMULATIONS[1], 'disabled': True}
    ],
    'future': [
        {**BASE_SIMULATIONS[0], 'disabled': True},
        {**BASE_SIMULATIONS[1], 'disabled': False}
    ],
    'both': [
        {**sim, 'disabled': False} for sim in BASE_SIMULATIONS
    ],
}

RECENT_WEATHER_STATIONS = [
    '13729',
    '13739',
    '13781',
    '14734',
    '14735',
    '14737',
    '14751',
    '14777',
    '14778',
    '14852',
    '14860',
    '4725',
    '4751',
    '93721',
    '93730',
    '93738',
    '94728',
    '94823',
]
FUTURE_WEATHER_STATIONS = [
    '13739',
    '13781',
    '14734',
    '14735',
    '14737',
    '14751',
    '14777',
    '14778',
    '4725',
    '93730',
    '94728',
]
COMMON_WEATHER_STATIONS = list(
    set(RECENT_WEATHER_STATIONS) & set(FUTURE_WEATHER_STATIONS)
)

def weather_update_sql(stations_list, simulation_key):
    stations = ",".join(stations_list)
    simulations = json.dumps(WEATHER_SIMULATIONS[simulation_key])

    return f"""
        UPDATE modeling_project
        SET weather_simulations = '{simulations}'::jsonb
        WHERE model_package = 'gwlfe'
          AND (
            SELECT COUNT(station_id)
            FROM (
                SELECT (station_data ->> 'station')::int AS station_id
                FROM JSONB_ARRAY_ELEMENTS(gis_data::jsonb -> 'WeatherStations') as station_data
            ) AS stations_in_project
            WHERE station_id = ANY(ARRAY[{stations}])
          ) = 2;
    """


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0045_initialize_pointsource_type_for_scenarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='weather_simulations',
            field=models.JSONField(
                default=list,
                help_text='JSON array of simulation groups available for project',
            ),
        ),
        # First set all GWLFE projects to have neither enabled (the deafult value)
        migrations.RunSQL(
            f"""
            UPDATE modeling_project
            SET weather_simulations = '{json.dumps(WEATHER_SIMULATIONS["neither"])}'::jsonb
            WHERE model_package = 'gwlfe';
        """
        ),
        # Then set those eligible for recent weather
        # This query checks if both stations for the project are in recent
        migrations.RunSQL(weather_update_sql(RECENT_WEATHER_STATIONS, 'recent')),
        # Then set those eligible for future weather
        migrations.RunSQL(weather_update_sql(FUTURE_WEATHER_STATIONS, 'future')),
        # Finally set those eligible for both
        migrations.RunSQL(weather_update_sql(COMMON_WEATHER_STATIONS, 'both')),
    ]
