---
- hosts: tile-servers
  become: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Create a node_modules directory
      file:
        path: "/opt/tiler/node_modules"
        state: directory
        owner: "vagrant"
        group: "vagrant"
      when: "['development', 'test'] | some_are_in(group_names)"

    - name: Create a node_modules cache directory
      file:
        path: "/var/cache/node_modules"
        state: directory
        owner: "vagrant"
        group: "vagrant"
        mode: "0755"
      when: "['development', 'test'] | some_are_in(group_names)"

  roles:
    - { role: "model-my-watershed.tiler" }
