---
- hosts: workers
  become: True

  vars:
    papertrail_files:
      - "/var/log/celery/*.log"

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - { role: "model-my-watershed.geoprocessing" }
    - { role: "model-my-watershed.celery-worker" }
    - { role: "model-my-watershed.rwd" }
